language: php

php:
    - 7.2
    - 7.3

notifications:
    email: false

before_install:
    - curl -L https://github.com/beanstalkd/beanstalkd/archive/v1.11.tar.gz | tar -xz -C /tmp
    - cd /tmp/beanstalkd-1.11
    - make
    - ./beanstalkd &
    - cd $TRAVIS_BUILD_DIR

install: composer install

script: make travis
